DEFERRED_EXEC_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes

SRC += matrix.c
LTO_ENABLE = yes

QMK_SETTINGS = yes

TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
EXTRAKEY_ENABLE = yes
MAGIC_ENABLE = yes
GRAVE_ESC_ENABLE = yes
MOUSEKEY_ENABLE = yes
NKRO_ENABLE = yes


RGBLIGHT_ENABLE = yes

AUDIO_ENABLE = yes

RGB_MATRIX_ENABLE = yes

#
ENCODER_MAP_ENABLE = yes
ENCODER_ENABLE = yes
